### ISSUE TITLE
With the acquisition by Solarwinds, will this repository location change?

### ISSUE THREAD

**Issue by jeffwidman** [VividCortex/mysqlerr#7]
In `go`, repository URLs matter. With the acquisition by SolarWinds, will this repository (and the others in the `VividCortext` org be moving under the https://github.com/solarwinds github org?

If so, can that be done sooner rather than later? The longer it's delayed, the more folks who start using the older URL and hence the greater the migration pain...

**Comment by pmatseykanets** [comment]
AFAIK there are no immediate plans to move this repository or others to the SWI GitHub org.
